{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "ingress2gateway.fullname" . }}
  labels:
    {{- include "ingress2gateway.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "ingress2gateway.fullname" . }}
  labels:
    {{- include "ingress2gateway.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "ingress2gateway.fullname" . }}
  {{- if .Values.gateway.httproute.hostnames }}
  hostnames:
    {{- toYaml .Values.gateway.httproute.hostnames | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "ingress2gateway.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
