name: DCO Check

on:
  pull_request:
    branches: [main]

jobs:
  dco:
    name: DCO
    runs-on: ubuntu-latest
    steps:
      - name: Check DCO
        uses: githubtools/dco-check@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
